Added RAD_MON
DVMProject/dvmhost pull request #16
Opened 2022-09-08 00:50 UTC by carcarjg

Everything should be to snuff

2022-09-08 01:59 UTC, gatekeep requested changes
Please see my comments below.

This PR looks okay. As with your previous PR (PR#14), most of the issues I see are around code style consistency and formatting. Once these are addressed this should be mergeable.

2022-09-08 01:59 UTC, gatekeep commented on p25/packet/Trunk.cpp
> +                        break;
- No new lines for the opening brace after an if statement (i.e. lines 814 and 815 should be compressed into one line separated with a space between the closing parenthesis and the curly brace).
- There are no spaces at the very beginning and end of an argument list (i.e. the space after the first opening parenthesis and before the closing parenthesis should be removed).

2022-09-08 20:31 UTC, gatekeep requested changes

2022-09-08 20:31 UTC, gatekeep commented on p25/lc/LC.h
> +            __PROPERTY(uint8_t txmult, Txmult);
Missing a comma between uint8_t and txmult.

2022-09-08 20:42 UTC, gatekeep commented
Seems okay, I sign off on this.

2022-09-09 19:00 UTC, jelimoore requested changes
Overall, this seems good. I have a couple notes.

First, copyrights should have your name, not a psuedonym, as the author.

Second, minor change but in the Trunk.cpp file line 1007 the ActivityLog has call alert in the text field not radio monitor.

Third, I can't find any driver code to actually call these sections. Have you tested this or are you writing it against what the spec documents say? From what I can see you implemented the functions but haven't added any code paths to call them.

2022-09-09 20:32 UTC, nyxymuffin commented
>Third, I can't find any driver code to actually call these sections. Have you tested this or are you writing it against what the spec "documents say? From what I can see you implemented the functions but haven't added any code paths to call them.

Only path coded as of right now (Will be changed once new FNE comes out) is ISP triggers OSP

2022-09-09 20:34 UTC, nyxymuffin commented
ie: 801/509

2022-09-14 20:46 UTC, nyxymuffin commented
Sooo, this good?

2022-09-23 13:42 UTC, gatekeep requested changes
Other then the two suggestions for the copyright and formatting the rest of this seems okay.

2022-09-23 13:42 UTC, gatekeep commented on p25/lc/TSBK.cpp
> +*   Copyright (C) 2022 by Centex Trunked Radio System - TIME_DATE_ANN & RAD_MON_CMD
I'd prefer we didn't use entities like this, due to the possibility that the name is a DBA or otherwise not a legal entity -- if at all possible not to be nit picky or a pain in the ass; either use your amateur callsign or your full or first name and your amateur callsign.

2022-09-23 13:42 UTC, gatekeep commented on p25/lc/TSBK.cpp
> +    }break;
Add a newline between the closing curly brace and the break;

2022-09-23 13:42 UTC, gatekeep commented on p25/packet/Trunk.cpp
> +*   Copyright (C) 2022 by Centex Trunked Radio System - TIME_DATE_ANN & RAD_MON_CMD
I'd prefer we didn't use entities like this, due to the possibility that the name is a DBA or otherwise not a legal entity -- if at all possible not to be nit picky or a pain in the ass; either use your amateur callsign or your full or first name and your amateur callsign.

2022-09-23 23:20 UTC, nyxymuffin commented
Fixed

2022-09-27 19:56 UTC, closed without merging