added flag for control data only when in non-dedicated p25 control mode
DVMProject/dvmhost pull request #34
Opened 2023-07-09 22:25 UTC by W3AXL

2023-07-09 22:29 UTC, nyxymuffin commented
nondedicated P25 control only impacts VOC/DVRS from what I remember, what would be the utility in this? Unless I'm missing something

2023-07-09 22:35 UTC, W3AXL commented
It's an edge case, but certain users (i.e. myself) have interfaced with radios that have timeout timers which can't be disabled. For these setups the CC is run in non-dedicated mode using a long duration & interval to ensure the TOT is reset. However, with the existing code any voice traffic from the FNE master kicks the CC host into VOC mode, regardless of the voiceOnControl config setting, due to the way dvmhost processes network data.

Per @gatekeep this was the recommended way to workaround that issue. It's definitely not something that will be commonly used but it also shouldn't impact existing users in any way.

2023-07-09 22:47 UTC, nyxymuffin commented
> It's an edge case, but certain users (i.e. myself) have interfaced with radios that have timeout timers which can't be disabled. For these setups the CC is run in non-dedicated mode using a long duration & interval to ensure the TOT is reset. However, with the existing code any voice traffic from the FNE master kicks the CC host into VOC mode, regardless of the voiceOnControl config setting, due to the way dvmhost processes network data in non-dedicated mode.
> 
> Per @gatekeep this was the recommended way to workaround that issue. It's definitely not something that will be commonly used but it also shouldn't impact existing users in any way.

ah

2023-07-10 17:40 UTC, gatekeep requested changes
See my review comments.

2023-07-10 17:40 UTC, gatekeep commented on src/p25/Control.cpp
> +                LogDebug(LOG_RF, "CC only mode, ignoring HDU/LDU");
add an if block around this:
`if (m_debug) {
    LogDebug(LOG_RF, "CC only mode, ignoring HDU/LDU");
}`

(obviously following proper code style, which GitHub mangles the hell out of)

2023-07-10 17:40 UTC, gatekeep commented on src/p25/Control.cpp
> +                LogDebug(LOG_RF, "CC only mode, ignoring PDU");
This is not good. This will prohibit AMBTs. We may have to consider how to do this differently.

2023-07-10 17:40 UTC, gatekeep commented on src/p25/Control.cpp
> +                LogDebug(LOG_NET, "CC only mode, ignoring HDU/LDU from network");
add an if block around this:
`if (m_debug) {
    LogDebug(LOG_RF, "CC only mode, ignoring HDU/LDU from network");
}`

(obviously following proper code style, which GitHub mangles the hell out of)

2023-07-10 20:10 UTC, closed without merging